name: LTeams
main: org.eldrygo.LTeams.LTeams
version: 0.0.01
api-version: 1.20
authors: [Drygo]
depend:
  - xTeams
  - LuckPerms
commands:
  lteams:
    description: "Plugin command."
permissions:
  lteams.reload:
    default: false
  lteams.sync:
    default: false